/*
 *
 * SponsorsPage reducer
 *
 */

import { fromJS } from 'immutable';
import {
  DEFAULT_ACTION, SUBMIT_ACTION,
} from './constants';

const initialState = fromJS({
  storageData: [
    {
      id: 1,
      date: '2019-01-17T23:03:23.000Z',
      filials: 'г.Киев, пер.Куренёвский, 17',
      filialManager: 'г.Одесса/ул.Дальницкая, 30',
      managerName: 'Фамилия И.О ',
      material: [
        {
          id: 1,
          account: 'ЛДСП 2800x2070x18 4023 OW Шварцвальд (SWISS KRONO)',
          amountAccount: '1555',
          cut: '10/01/19',
          amountCut: '5555',
          dirEdge: '02/01/19',
          amountDirEdge: '555',
          crEdge: '',
          amountCrEdge: '55',
          hole: '10/01/19',
          amountHole: '5',
          milling: '',
          amountMilling: '',
          pack: '02/01/19',
          amountPack: '555',
          dateStatus: '2019-01-20T23:03:23.000Z',
          status: 'Производство',
          description: '',
        },
        {
          id: 2,
          account: 'ЛДСП 2800x2070x18 4023 OW Шварцвальд (SWISS KRONO)',
          amountAccount: '55',
          cut: '',
          amountCut: '5555',
          dirEdge: '02/01/19',
          amountDirEdge: '555',
          crEdge: '02/01/19',
          amountCrEdge: '55',
          hole: '',
          amountHole: '5',
          milling: '10/01/19',
          amountMilling: '',
          pack: '02/01/19',
          amountPack: '555',
          dateStatus: '',
          status: 'Укомплектован',
          description: '',
        },
        {
          id: 3,
          account: 'ЛДСП 2800x2070x18 4023 OW Шварцвальд (SWISS KRONO)',
          amountAccount: '55',
          cut: '10/01/19',
          amountCut: '5555',
          dirEdge: '02/01/19',
          amountDirEdge: '555',
          crEdge: '',
          amountCrEdge: '55',
          hole: '10/01/19',
          amountHole: '5',
          milling: '',
          amountMilling: '',
          pack: '02/01/19',
          amountPack: '555',
          dateStatus: '2019-01-18T23:03:23.000Z',
          status: 'Комплектация',
          description: '',
        },
        {
          id: 4,
          account: 'ЛДСП 2800x2070x18 4023 OW Шварцвальд (SWISS KRONO)',
          amountAccount: '55',
          cut: '10/01/19',
          amountCut: '5555',
          dirEdge: '02/01/19',
          amountDirEdge: '555',
          crEdge: '02/01/19',
          amountCrEdge: '55',
          hole: '10/01/19',
          amountHole: '5',
          milling: '',
          amountMilling: '',
          pack: '',
          amountPack: '555',
          dateStatus: '',
          status: 'Планирование',
          description: '',
        },
        {
          id: 5,
          account: 'ЛДСП 2800x2070x18 4023 OW Шварцвальд (SWISS KRONO)',
          amountAccount: '55',
          cut: '10/01/19',
          amountCut: '5555',
          dirEdge: '02/01/19',
          amountDirEdge: '555',
          crEdge: '02/01/19',
          amountCrEdge: '55',
          hole: '10/01/19',
          amountHole: '5',
          milling: '',
          amountMilling: '',
          pack: '',
          amountPack: '555',
          dateStatus: '',
          status: 'Запланирован',
          description: '',
        },
        {
          id: 6,
          account: 'ЛДСП 2800x2070x18 4023 OW Шварцвальд (SWISS KRONO)',
          amountAccount: '55',
          cut: '10/01/19',
          amountCut: '5555',
          dirEdge: '02/01/19',
          amountDirEdge: '555',
          crEdge: '02/01/19',
          amountCrEdge: '55',
          hole: '10/01/19',
          amountHole: '5',
          milling: '',
          amountMilling: '',
          pack: '',
          amountPack: '555',
          dateStatus: '',
          status: 'В работе',
          description: '',
        },
      ],
    },
    {
      id: 22,
      date: '2019-01-18T23:03:23.000Z',
      filials: 'г.Киев, пер.Куренёвский, 17',
      filialManager: 'г.Одесса/ул.Дальницкая, 30',
      managerName: 'Фамилия И.О ',
      material: [
        {
          id: 12,
          filials: 'г.Киев/пер.Куренёвский, 17',
          account: 'ЛДСП 2800x2070x18 4023 OW Шварцвальд (SWISS KRONO)',
          amountAccount: '55',
          cut: '10/01/19',
          amountCut: '5555',
          dirEdge: '02/01/19',
          amountDirEdge: '555',
          crEdge: '02/01/19',
          amountCrEdge: '55',
          hole: '10/01/19',
          amountHole: '5',
          milling: '',
          amountMilling: '',
          pack: '02/01/19',
          amountPack: '555',
          filialManager: 'г.Одесса/ул.Дальницкая',
          managerName: 'Фамилия И.О ',
          dateStatus: '2019-01-19T23:03:23.000Z',
          status: 'Комплектация',
          description: '',
        },
        {
          id: 22,
          filials: 'г.Киев/пер.Куренёвский, 17',
          account: 'ЛДСП 2800x2070x18 4023 OW Шварцвальд (SWISS KRONO)',
          amountAccount: '55',
          cut: '10/01/19',
          amountCut: '5555',
          dirEdge: '',
          amountDirEdge: '555',
          crEdge: '02/01/19',
          amountCrEdge: '55',
          hole: '10/01/19',
          amountHole: '5',
          milling: '10/01/19',
          amountMilling: '',
          pack: '02/01/19',
          amountPack: '555',
          filialManager: 'г.Одесса/ул.Дальницкая',
          managerName: 'Фамилия И.О ',
          dateStatus: '',
          status: 'Доставка',
          description: '',
        },
      ],
    },
  ],

});

function storageReducer(state = initialState, action) {
  switch (action.type) {
    case SUBMIT_ACTION:
      return state.set('storageData', state.get('storageData').concat(action.storage));
    case DEFAULT_ACTION:
      return state;
    default:
      return state;
  }
}

export default storageReducer;
