/*
 *
 * ManufacturePage reducer
 *
 */

import { fromJS } from 'immutable';
import {
  DEFAULT_ACTION, CHANGE_DATE_RANGE,
} from './constants';

const initialState = fromJS({
  dateRange: { from: null, to: null },
  manufactureData: [
    {
      id: '1',
      manufactureStatus: '1',
      date: '2019-01-17T23:03:23.000Z',
      materialManuf: [
        {
          id: '1',
          account: 'ЛДСП 2800x2070x18 4028 OW Сосна Водевиль (SWISS KRONO)',
          cut: 'Сделано',
          dateCut: '10/01/19',
          changeCut: 'Cмена №19 Brandt',
          deviant: true,
          dirEdge: 'В работу',
          dateDirEdge: '10/01/19',
          changeDirEdge: 'Cмена №19 Brandt',
          deviantEdge: false,
          crEdge: 'Не включено в план',
          dateCrEdge: '10/01/19',
          changeCrEdge: 'Cмена №19 Brandt',
          deviantCrEdge: true,
          hole: 'Сделано',
          dateHole: '10/01/19',
          changeHole: 'Cмена №19 Brandt',
          deviantHole: true,
          milling: 'В работу',
          dateMilling: '10/01/19',
          changeMilling: 'Cмена №19 Brandt',
          deviantMilling: false,
          pack: 'Сделано',
          datePack: '10/01/19',
          changePack: 'Cмена №19 Brandt',
          deviantPack: true,
        },
        {
          id: '2',
          account: 'ЛДСП 2800x2070x18 4027 OW Ильм Амальфи (SWISS KRONO)',
          cut: 'Сделано',
          dateCut: '10/01/19',
          changeCut: 'Cмена №19 Brandt',
          deviant: true,
          dirEdge: 'В работу',
          dateDirEdge: '10/01/19',
          changeDirEdge: 'Cмена №19 Brandt',
          deviantDirEdge: false,
          crEdge: 'Сделано',
          dateCrEdge: '10/01/19',
          changeCrEdge: 'Cмена №19 Brandt',
          deviantCrEdge: true,
          hole: 'Не включено в план',
          dateHole: '10/01/19',
          changeHole: 'Cмена №19 Brandt',
          deviantHole: true,
          milling: 'В работу',
          dateMilling: '10/01/19',
          changeMilling: 'Cмена №19 Brandt',
          deviantMilling: false,
          pack: 'Сделано',
          datePack: '10/01/19',
          changePack: 'Cмена №19 Brandt',
          deviantPack: true,
        },
        {
          id: '3',
          account: 'ЛДСП 2800x2070x18 4026 MX Сосна Лейкербад (SWISS KRONO)',
          cut: 'Сделано',
          dateCut: '10/01/19',
          changeCut: 'Cмена №19 Brandt',
          deviant: true,
          dirEdge: 'В работу',
          dateDirEdge: '10/01/19',
          changeDirEdge: 'Cмена №19 Brandt',
          deviantEdge: false,
          crEdge: 'Сделано',
          dateCrEdge: '10/01/19',
          changeCrEdge: 'Cмена №19 Brandt',
          deviantCrEdge: true,
          hole: 'Не включено в план',
          dateHole: '10/01/19',
          changeHole: 'Cмена №19 Brandt',
          deviantHole: true,
          milling: 'В работу',
          dateMilling: '10/01/19',
          changeMilling: 'Cмена №19 Brandt',
          deviantMilling: false,
          pack: 'Сделано',
          datePack: '10/01/19',
          changePack: 'Cмена №19 Brandt',
          deviantPack: true,
        },
      ],
    },
    {
      id: '2',
      manufactureStatus: '2',
      date: '2019-01-18T23:03:23.000Z',
      materialManuf: [{
        id: '1',
        account: 'ЛДСП 2800x2070x18 4028 OW Сосна Водевиль (SWISS KRONO)',
        cut: 'Сделано',
        dateCut: '10/01/19',
        changeCut: 'Cмена №19 Brandt',
        deviant: true,
        dirEdge: 'В работу',
        dateDirEdge: '10/01/19',
        changeDirEdge: 'Cмена №19 Brandt',
        deviantEdge: false,
        crEdge: 'Сделано',
        dateCrEdge: '10/01/19',
        changeCrEdge: 'Cмена №19 Brandt',
        deviantCrEdge: true,
        hole: 'Сделано',
        dateHole: '10/01/19',
        changeHole: 'Cмена №19 Brandt',
        deviantHole: true,
        milling: 'В работу',
        dateMilling: '10/01/19',
        changeMilling: 'Cмена №19 Brandt',
        deviantMilling: false,
        pack: 'Сделано',
        datePack: '10/01/19',
        changePack: 'Cмена №19 Brandt',
        deviantPack: true,
      },
      {
        id: '2',
        account: 'ЛДСП 2800x2070x18 4027 OW Ильм Амальфи (SWISS KRONO)',
        cut: 'Сделано',
        dateCut: '10/01/19',
        changeCut: 'Cмена №19 Brandt',
        deviant: true,
        dirEdge: 'В работу',
        dateDirEdge: '10/01/19',
        changeDirEdge: 'Cмена №19 Brandt',
        deviantEdge: false,
        crEdge: 'Не включено в план',
        dateCrEdge: '10/01/19',
        changeCrEdge: 'Cмена №19 Brandt',
        deviantCrEdge: true,
        hole: 'Сделано',
        dateHole: '10/01/19',
        changeHole: 'Cмена №19 Brandt',
        deviantHole: true,
        milling: 'В работу',
        dateMilling: '10/01/19',
        changeMilling: 'Cмена №19 Brandt',
        deviantMilling: false,
        pack: 'Сделано',
        datePack: '10/01/19',
        changePack: 'Cмена №19 Brandt',
        deviantPack: true,
      },
      ],
    },
    {
      id: '3',
      manufactureStatus: '1',
      date: '2019-01-19T23:03:23.000Z',
      materialManuf: [{
        id: '1',
        account: 'ЛДСП 2800x2070x18 4027 OW Ильм Амальфи (SWISS KRONO)',
        cut: 'Сделано',
        dateCut: '10/01/19',
        changeCut: 'Cмена №19 Brandt',
        deviant: true,
        dirEdge: 'В работу',
        dateDirEdge: '10/01/19',
        changeDirEdge: 'Cмена №19 Brandt',
        deviantEdge: false,
        crEdge: 'Сделано',
        dateCrEdge: '10/01/19',
        changeCrEdge: 'Cмена №19 Brandt',
        deviantCrEdge: true,
        hole: 'Сделано',
        dateHole: '10/01/19',
        changeHole: 'Cмена №19 Brandt',
        deviantHole: true,
        milling: 'В работу',
        dateMilling: '10/01/19',
        changeMilling: 'Cмена №19 Brandt',
        deviantMilling: false,
        pack: 'Сделано',
        datePack: '10/01/19',
        changePack: 'Cмена №19 Brandt',
        deviantPack: true,
      },
      {
        id: '2',
        account: 'ЛДСП 2800x2070x18 4027 OW Ильм Амальфи (SWISS KRONO)',
        cut: 'Сделано',
        dateCut: '10/01/19',
        changeCut: 'Cмена №19 Brandt',
        deviant: true,
        dirEdge: 'В работу',
        dateDirEdge: '10/01/19',
        changeDirEdge: 'Cмена №19 Brandt',
        deviantEdge: false,
        crEdge: 'Сделано',
        dateCrEdge: '10/01/19',
        changeCrEdge: 'Cмена №19 Brandt',
        deviantCrEdge: true,
        hole: 'Сделано',
        dateHole: '10/01/19',
        changeHole: 'Cмена №19 Brandt',
        deviantHole: true,
        milling: 'Не включено в план',
        dateMilling: '10/01/19',
        changeMilling: 'Cмена №19 Brandt',
        deviantMilling: false,
        pack: 'Сделано',
        datePack: '10/01/19',
        changePack: 'Cмена №19 Brandt',
        deviantPack: true,
      },
      ],
    },
  ],
});

function manufacturePageReducer(state = initialState, action) {
  switch (action.type) {
    case DEFAULT_ACTION:
      return state;
    case CHANGE_DATE_RANGE:
      return state.set('dateRange', action.dateRange);
    default:
      return state;
  }
}

export default manufacturePageReducer;
